import { SungkaBoard, ISungkaBoard } from "../../ui/sungka-board/SungkaBoard";

import BoardImage from "../../../assets/images/boards/old-wood-01.png";
import Shell from "../../../assets/images/shells/white-shell.png";

let data: ISungkaBoard = {
  boardBackgroundImage: "url(" + BoardImage + ")",
  boardWidth: 1440,
  boardHeight: 600,
  holesData: [
    {
      holeId: "ulo-p1",
      holeClassName: "ulo-p1-hole",
      containmentAreaRadius: 12.5,
      counterCount: 2,
      counterWidth: 25,
      counterHeight: 25,
      counterImgSrc: "url(" + Shell + ")",
    },
    {
      holeId: "ulo-p2",
      holeClassName: "ulo-p2-hole",
      containmentAreaRadius: 12.5,
      counterCount: 4,
      counterWidth: 25,
      counterHeight: 25,
      counterImgSrc: "url(" + Shell + ")",
    },

    {
      holeId: "bahay01",
      holeClassName: "bahay01",
      containmentAreaRadius: 12.5,
      counterCount: 4,
      counterWidth: 25,
      counterHeight: 25,
      counterImgSrc: "url(" + Shell + ")",
    },
    {
      holeId: "bahay02",
      holeClassName: "bahay02",
      containmentAreaRadius: 12.5,
      counterCount: 4,
      counterWidth: 25,
      counterHeight: 25,
      counterImgSrc: "url(" + Shell + ")",
    },

    {
      holeId: "bahay03",
      holeClassName: "bahay03",
      containmentAreaRadius: 12.5,
      counterCount: 4,
      counterWidth: 25,
      counterHeight: 25,
      counterImgSrc: "url(" + Shell + ")",
    },
    {
      holeId: "bahay04",
      holeClassName: "bahay04",
      className: "bahay04",
      containmentAreaRadius: 12.5,
      counterCount: 0,
      counterWidth: 25,
      counterHeight: 25,
      counterImgSrc: "url(" + Shell + ")",
    },
    {
      holeId: "bahay05",
      holeClassName: "bahay05",
      className: "bahay05",
      containmentAreaRadius: 12.5,
      counterCount: 0,
      counterWidth: 25,
      counterHeight: 25,
      counterImgSrc: "url(" + Shell + ")",
    },
    {
      holeId: "bahay06",
      holeClassName: "bahay06",
      className: "bahay06",
      containmentAreaRadius: 12.5,
      counterCount: 28,
      counterWidth: 25,
      counterHeight: 25,
      counterImgSrc: "url(" + Shell + ")",
    },
    {
      holeId: "bahay07",
      holeClassName: "bahay07",
      className: "bahay07",
      containmentAreaRadius: 12.5,
      counterCount: 7,
      counterWidth: 25,
      counterHeight: 25,
      counterImgSrc: "url(" + Shell + ")",
    },
    {
      holeId: "bahay08",
      holeClassName: "bahay08",
      className: "bahay08",
      containmentAreaRadius: 12.5,
      counterCount: 7,
      counterWidth: 25,
      counterHeight: 25,
      counterImgSrc: "url(" + Shell + ")",
    },
    {
      holeId: "bahay09",
      holeClassName: "bahay09",
      className: "bahay09",
      containmentAreaRadius: 12.5,
      counterCount: 7,
      counterWidth: 25,
      counterHeight: 25,
      counterImgSrc: "url(" + Shell + ")",
    },
    {
      holeId: "bahay10",
      holeClassName: "bahay10",
      className: "bahay10",
      containmentAreaRadius: 12.5,
      counterCount: 7,
      counterWidth: 25,
      counterHeight: 25,
      counterImgSrc: "url(" + Shell + ")",
    },
    {
      holeId: "bahay11",
      holeClassName: "bahay11",
      className: "bahay11",
      containmentAreaRadius: 12.5,
      counterCount: 7,
      counterWidth: 25,
      counterHeight: 25,
      counterImgSrc: "url(" + Shell + ")",
    },
    {
      holeId: "bahay12",
      holeClassName: "bahay12",
      className: "bahay12",
      containmentAreaRadius: 12.5,
      counterCount: 7,
      counterWidth: 25,
      counterHeight: 25,
      counterImgSrc: "url(" + Shell + ")",
    },
    {
      holeId: "bahay13",
      holeClassName: "bahay13",
      className: "bahay13",
      containmentAreaRadius: 12.5,
      counterCount: 7,
      counterWidth: 25,
      counterHeight: 25,
      counterImgSrc: "url(" + Shell + ")",
    },
    {
      holeId: "bahay14",
      holeClassName: "bahay14",
      className: "bahay14",
      containmentAreaRadius: 12.5,
      counterCount: 7,
      counterWidth: 25,
      counterHeight: 25,
      counterImgSrc: "url(" + Shell + ")",
    },
  ],
};

export const Play = (props: any) => {
  return <SungkaBoard {...data} />;
};
