runtime: nodejs16

instance_class: F2

env_variables:
  PUBLIC_FIREBASE_API_KEY: "AIzaSyDU7svu9g-jM96lZS-OVhFDlrKZW_YSG5c"
  PUBLIC_FIREBASE_AUTH_DOMAIN: "sungka-app.firebaseapp.com"
  PUBLIC_FIREBASE_PROJECT_ID: "sungka-app"
  PUBLIC_FIREBASE_STORAGE_BUCKET: "sungka-app.appspot.com"
  PUBLIC_FIREBASE_MESSAGING_SENDER_ID: "250834379578"
  PUBLIC_FIREBASE_APP_ID: "1:250834379578:web:ec85fc04545d38265a2603"

handlers:
  - url: /(.*\..+)$
    static_files: build/\1
    upload: build/(.*\..+)$
  - url: /.*
    static_files: build/index.html
    upload: build/index.html
